### ISSUE TITLE
AttributeError: module 'pyspark.sql.utils' has no attribute 'convert_exception'

### ISSUE THREAD

**Issue by omsec** [handreassa/delta-docker#1]
When executing the first cell of the notebook, I get this error message. I've tried to change the packages as shown [here](https://stackoverflow.com/questions/77129526/which-combination-of-pyspark-and-delta-versions-should-i-use), but that didn't help.

**Comment by handreassa** [comment]
Hey there @omsec , fixes applied. Can you please test it again? Also added some comments in that stackoverflow question. Any question please let me know!
