### ISSUE TITLE
Error "http: invalid Host header" when I run "docker-compose up --build" command

### ISSUE THREAD

**Issue by trongtran** [handreassa/delta-docker#2]
Please give your help to how to solve this issue. Thanks

------
$ docker-compose up --build
[+] Building 14.7s (1/1) FINISHED                                                                                                                                                        
 => ERROR [internal] booting buildkit                                                                                                                                              14.7s
 => => starting container buildx_buildkit_default                                                                                                                                  14.7s
------
 > [internal] booting buildkit:
#0 14.71 time="2023-10-16T07:42:04Z" level=warning msg="using host network as the defaultime="2023-10-16T07:42:04Z" level=warning msg="using host network as the default"
#0 14.71 time="2023-10-16T07:42:04Z" level=warning msg="skipping containerd worker, as \"/run/containerd/containerd.sock\" does not exist"
#0 14.71 dtime="2023-10-16T07:42:04Z" level=info msg="found 1 workers, default=\"r7kkur71sfdwb4nrfw3gft3ci\""
#0 14.71 time="2023-10-16T07:42:04Z" level=warning msg="skipping containerd worker, as \"/run/containerd/containerd.sock\" does not exist"
#0 14.71 time="2023-10-16T07:42:04Z" level=info msg="running server on /run/buildkit/buildkitd.sock"
#0 14.71 time="2023-10-16T07:42:04Z" level=info msg="running server on /run/buildkit/buildkitd.sock"
#0 14.71 buildkitd: context canceled
#0 14.71 Otime="2023-10-16T08:04:38buildkitd: context canceled
#0 14.71 time="2023-10-16T08:04:38Z" level=warning msg="using host network as the defaultime="2023-10-16T08:04:38Z" level=warning msg="using host network as the default"
#0 14.71 time="2023-10-16T08:04:38Z" level=warning msg="skipping containerd worker, as \"/run/containerd/containerd.sock\" does not exist"
#0 14.71 dtime="2023-10-16T08:04:38Z" level=info msg="found 1 workers, default=\"r7kkur71sfdwb4nrfw3gft3ci\""
#0 14.71 `time="2023-10-16T08:04:38Z" level=warning msg="currently, only the default worker can be used."
#0 14.71 \time="2023-10-16T08:04:38Z" level=info msg="running server on /run/buildkit/buildkitd.sock"
#0 14.71 =time="2023-10-16T08:13:58Z" level=info mtime="2023-10-16T08:04:38Z" level=warning msg="skipping containerd worker, as \"/run/containerd/containerd.sock\" does not exist"
#0 14.71 time="2023-10-16T08:04:38Z" level=warning msg="currently, only the default worker can be used."
#0 14.71 time="2023-10-16T08:04:38Z" level=warning msg="currently, only the default worker can be used."
#0 14.71 time="2023-10-16T08:13:58Z" level=info msg="stopping server"
#0 14.71 buildkitd: context canctime="2023-10-16T08:13:58Z" level=info msg="stopping server"
#0 14.71 time="2023-10-16T08:14:02Z" time="2023-10-16T08:14:02Z" level=info msg="auto snapshotter: using overlayfs"
#0 14.71 time="2023-10-16T08:14:02Z" level=info msg="found worker \"r7kkur71sfdwb4nrfw3gft3time="2023-10-16T08:14:02Z" level=info msg="found worker \"r7kkur71sfdwb4nrfw3gft3ci\", labels=map[org.mobyproject.buildkit.worker.executor:oci org.mobyproject.buildkit.worker.hostname:c081765bbac3 org.mobyproject.buildkit.worker.network:host org.mobyproject.buildkit.worker.oci.process-mode:sandbox org.mobyproject.buildkit.worker.selinux.enabled:false org.mobyproject.buildkit.worker.snapshotter:overlayfs], platforms=[linux/amd64 linux/amd64/v2 linux/amd64/v3 linux/amd64/v4 linux/386]"
#0 14.71 time="2023-10-16T08:14:02Z" level=info msg="found 1 workers, default=\"r7kkur71sfdwb4nrfw3gft3ci\""
#0 14.71 `time="2023-10-16T08:14time="2023-10-16T08:14:02Z" level=info msg="found 1 workers, default=\"r7kkur71sfdwb4nrfw3gft3ci\""
#0 14.71 time="2023-10-16T08:14:02Z" level=info msg="running server on /run/buildkit/buildkitd.sock"
#0 14.71 time="2023-10-16T08:14:02Z" level=info msg="running server on /run/buildkit/buildkitd.sock"
------
http: invalid Host header

**Comment by handreassa** [comment]
Hi @trongtran, tried to do a clean run here and haven't faced any issued connecting to it. Would you mind trying the solution described here https://stackoverflow.com/questions/77289337/docker-compose-error-internal-booting-buildkit-http-invalid-host-header-whil? If it doesn't work, please share more details on the docker version you are using or try to run the official Jupyter image since it's where the network is required. Anything please let me know!

**Comment by handreassa** [comment]
@trongtran is this still happening?
